### ISSUE TITLE
Playlist not work 

### ISSUE THREAD

**Issue by ghost** [razum90/SupahBot#1]
Playlist from youtube don't work and !video crash bot

**Comment by ghost** [comment]
[ss-bota-logs-1517321607143.txt](https://github.com/razum90/SupahBot/files/1677978/ss-bota-logs-1517321607143.txt)
idk why crash

**Comment by razum90** [comment]
Hi @donkeymonkey1. Firstly the bot does not support to queue a playlist from youtube - yet. Please provide the full logs of the crash if you want help, thanks!
